services:
  - type: web
    name: blogs-backend
    runtime: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 10000
